name: wizard_builder
description: A wizard builder widget to easily create a wizard (with nested navigation).
version: 2.0.1
homepage: https://github.com/baku-apps/wizard_builder

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: